import React,{useState} from 'react';
import {useLanguage,AppLanguage} from '../contexts/LanguageContext';

type Copy={ [key:string]:string|string[] };
const COPY:Record<AppLanguage,Copy>={
 English:{welcome:'Welcome to NUVYRA',headline:'Your body has patterns.',sub:'NUVYRA helps you notice them.',intro:'A guided tour of the system, what each area does, and how your personal baseline is built.',explore:'Start guided tour →',skip:'Skip tour',next:'Next →',finish:'Finish & open NUVYRA ✦',step1:'How NUVYRA works',step1Text:'NUVYRA combines repeated self-reported context with available voice and camera signals. It checks data quality, compares observations with your own history, and looks for changes that persist over time.',step2:'Your NUVYRA navigation',step2Text:'These are the main areas you can use after registration. Tap any feature to see what it is for.',step3:'Your personal baseline',step3Text:'Your baseline is your own usual pattern learned from repeated usable check-ins. NUVYRA does not require you to match a population average.',step4:'Quick guide',step4Text:'These cards are a quick reminder of what the system does.',features:['Dashboard — your current overview','Daily Check-in — record today’s context and signals','Biomarkers — understand what each measurement means','Trends — view changes across your history','Timeline — see completed check-ins in sequence','Clinical View — organize clinical context for review','Past History — keep previous history and documents organized','AI Companion — ask general health and NUVYRA questions','Notifications — see reminders and system updates','Reports — export longitudinal observation summaries'],cards:['What is NUVYRA?','What is a personal baseline?','What does the check-in collect?','Is NUVYRA a diagnosis?'],backs:['A health-technology prototype for organizing repeated observations over time.','Your own usual pattern learned from repeated usable measurements.','Self-report plus available voice and camera signals, with quality checks.','No. It presents observations and changes for review; it does not diagnose conditions.']},
 Hindi:{welcome:'NUVYRA में आपका स्वागत है',headline:'आपके शरीर के अपने पैटर्न होते हैं।',sub:'NUVYRA आपको उन्हें समझने में मदद करता है।',intro:'सिस्टम का निर्देशित परिचय, हर हिस्से का काम और आपकी व्यक्तिगत बेसलाइन कैसे बनती है।',explore:'निर्देशित टूर शुरू करें →',skip:'टूर छोड़ें',next:'अगला →',finish:'पूरा करें और NUVYRA खोलें ✦',step1:'NUVYRA कैसे काम करता है',step1Text:'NUVYRA बार-बार के स्वयं-रिपोर्ट किए गए संदर्भ को उपलब्ध आवाज़ और कैमरा संकेतों के साथ जोड़ता है। यह डेटा गुणवत्ता जाँचता है, आपकी अपनी हिस्ट्री से तुलना करता है और समय के साथ बने रहने वाले बदलाव देखता है।',step2:'आपका NUVYRA नेविगेशन',step2Text:'रजिस्ट्रेशन के बाद ये मुख्य हिस्से उपलब्ध हैं। किसी फीचर को दबाकर उसका काम जानें।',step3:'आपकी व्यक्तिगत बेसलाइन',step3Text:'आपकी बेसलाइन बार-बार के उपयोगी चेक-इन से सीखा गया आपका अपना सामान्य पैटर्न है। NUVYRA आपको किसी जनसंख्या औसत से मिलाने की आवश्यकता नहीं रखता।',step4:'क्विक गाइड',step4Text:'ये कार्ड सिस्टम के काम का छोटा रिमाइंडर हैं।',features:['डैशबोर्ड — वर्तमान ओवरव्यू','दैनिक चेक-इन — आज का संदर्भ और संकेत रिकॉर्ड करें','बायोमार्कर — हर माप का अर्थ समझें','ट्रेंड — इतिहास में बदलाव देखें','टाइमलाइन — पूरे किए गए चेक-इन क्रम में देखें','क्लिनिकल व्यू — क्लिनिकल संदर्भ समीक्षा के लिए व्यवस्थित करें','पिछला इतिहास — पुराना इतिहास और दस्तावेज़ व्यवस्थित रखें','AI साथी — सामान्य स्वास्थ्य और NUVYRA सवाल पूछें','सूचनाएँ — रिमाइंडर और सिस्टम अपडेट देखें','रिपोर्ट — लॉन्गिट्यूडिनल अवलोकन सारांश एक्सपोर्ट करें'],cards:['NUVYRA क्या है?','व्यक्तिगत बेसलाइन क्या है?','चेक-इन क्या रिकॉर्ड करता है?','क्या NUVYRA निदान करता है?'],backs:['समय के साथ बार-बार के अवलोकनों को व्यवस्थित करने वाला हेल्थ-टेक प्रोटोटाइप।','बार-बार के उपयोगी मापों से सीखा गया आपका अपना सामान्य पैटर्न।','स्वयं-रिपोर्ट के साथ उपलब्ध आवाज़ और कैमरा संकेत तथा डेटा गुणवत्ता जाँच।','नहीं। यह समीक्षा के लिए अवलोकन और बदलाव दिखाता है; बीमारी का निदान नहीं करता।']},
 French:{welcome:'Bienvenue sur NUVYRA',headline:'Votre corps a ses propres habitudes.',sub:'NUVYRA vous aide à les observer.',intro:'Une visite guidée du système, de chaque espace et de la façon dont votre référence personnelle est construite.',explore:'Commencer la visite →',skip:'Passer la visite',next:'Suivant →',finish:'Terminer et ouvrir NUVYRA ✦',step1:'Comment fonctionne NUVYRA',step1Text:'NUVYRA combine le contexte déclaré à plusieurs reprises avec les signaux vocaux et caméra disponibles. Il vérifie la qualité, compare vos observations à votre propre historique et recherche les changements persistants.',step2:'Votre navigation NUVYRA',step2Text:'Voici les principaux espaces disponibles après l’inscription. Touchez une fonction pour voir son rôle.',step3:'Votre référence personnelle',step3Text:'Votre référence personnelle correspond à votre fonctionnement habituel appris à partir de contrôles utilisables répétés. NUVYRA ne vous compare pas à une moyenne de population.',step4:'Guide rapide',step4Text:'Ces cartes résument rapidement le fonctionnement du système.',features:['Tableau de bord — votre aperçu actuel','Contrôle quotidien — enregistrez contexte et signaux du jour','Biomarqueurs — comprenez chaque mesure','Tendances — observez les changements dans votre historique','Chronologie — voyez les contrôles terminés dans l’ordre','Vue clinique — organisez le contexte clinique pour revue','Historique — organisez votre historique et vos documents','Compagnon IA — posez des questions générales sur la santé et NUVYRA','Notifications — consultez rappels et mises à jour','Rapports — exportez des résumés longitudinaux'],cards:['Qu’est-ce que NUVYRA ?','Qu’est-ce qu’une référence personnelle ?','Que recueille le contrôle ?','NUVYRA établit-il un diagnostic ?'],backs:['Un prototype de technologie de santé qui organise des observations répétées dans le temps.','Votre fonctionnement habituel appris à partir de mesures utilisables répétées.','Des données déclarées et les signaux vocaux et caméra disponibles, avec contrôle qualité.','Non. Il présente des observations et changements pour revue, sans diagnostiquer.']}
};
const featuresIcons=['⌂','◉','◌','⌁','⋮','▣','◫','✦','!','⇩'];

export default function NuvyraWelcome({onComplete}:{onComplete:()=>void}){
 const {language}=useLanguage();const t=COPY[language];const [step,setStep]=useState(0);const [open,setOpen]=useState<number|null>(null);const [flipped,setFlipped]=useState<number|null>(null);
 const next=()=>setStep(s=>s<4?s+1:4);
 const finish=()=>onComplete();
 return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center p-5 sm:p-8"><div className="w-full max-w-6xl">
  <div className="flex justify-between items-center mb-8"><span className="text-xs tracking-[.25em] text-slate-500">NUVYRA · {step+1}/5</span><button onClick={finish} className="text-sm text-slate-400 hover:text-white">{t.skip}</button></div>
  {step===0&&<section className="text-center py-8"><div className="text-6xl mb-5">✦</div><p className="uppercase tracking-[.3em] text-sm text-slate-400">{t.welcome}</p><h1 className="text-4xl md:text-6xl font-semibold tracking-tight mt-4">{t.headline}<br/><span className="text-slate-400">{t.sub}</span></h1><p className="max-w-2xl mx-auto text-base md:text-lg text-slate-300 mt-6">{t.intro}</p><div className="flex justify-center gap-3 mt-8"><button onClick={next} className="rounded-2xl px-7 py-4 bg-white text-slate-950 font-semibold">{t.explore}</button><button onClick={finish} className="rounded-2xl px-6 py-4 border border-slate-700 text-slate-300">{t.skip}</button></div></section>}
  {step===1&&<section><p className="text-slate-400 uppercase tracking-widest text-sm">NUVYRA</p><h2 className="text-4xl font-semibold mt-2">{t.step1}</h2><p className="text-slate-400 mt-3 max-w-3xl leading-6">{t.step1Text}</p><div className="grid md:grid-cols-3 gap-4 mt-8">{['🎙️ Voice & speech','🙂 Facial and eye signals','🧭 Movement, breathing and head signals'].map((x,i)=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="text-lg font-medium">{x}</div><p className="text-sm text-slate-400 mt-2">{i===0?'Observable speech characteristics are captured during a short recording.':i===1?'Camera-based proxies are estimated from visible facial and eye changes.':'Available visible motion and breathing-related proxies are estimated during the camera check.'}</p></div>)}</div><div className="flex justify-end mt-8"><button onClick={next} className="rounded-2xl px-7 py-3 bg-white text-slate-950 font-semibold">{t.next}</button></div></section>}
  {step===2&&<section><h2 className="text-4xl font-semibold">{t.step2}</h2><p className="text-slate-400 mt-3">{t.step2Text}</p><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 mt-8">{(t.features as string[]).map((feature,i)=>{const parts=feature.split(' — ');return <button key={feature} onClick={()=>setOpen(open===i?null:i)} className={`group aspect-square min-h-[145px] text-left rounded-[2rem] border bg-gradient-to-br from-slate-900 via-[#111827] to-slate-950 p-5 transition-all hover:-translate-y-1 hover:border-sky-500/50 hover:shadow-xl hover:shadow-sky-950/30 ${open===i?'border-sky-500/60 ring-1 ring-sky-500/20':'border-slate-800'}`}><div className="flex items-start justify-between gap-2"><span className="text-2xl text-sky-400">{featuresIcons[i]}</span><span className="text-[10px] uppercase tracking-wider text-slate-600">01{i+1}</span></div><div className="mt-6 text-sm font-semibold text-white leading-5">{parts[0]}</div><p className="mt-2 text-[11px] leading-4 text-slate-500">{open===i?(parts[1]||feature):'Tap to learn more'}</p></button>})}</div><div className="flex justify-end mt-8"><button onClick={next} className="rounded-2xl px-7 py-3 bg-white text-slate-950 font-semibold">{t.next}</button></div></section>}
  {step===3&&<section className="text-center py-8"><h2 className="text-4xl md:text-5xl font-semibold">{t.step3}</h2><div className="max-w-2xl mx-auto mt-8 rounded-3xl border border-sky-500/20 bg-sky-500/5 p-8"><div className="text-5xl">●</div><p className="text-slate-300 mt-5 leading-7">{t.step3Text}</p></div><div className="flex justify-end mt-8"><button onClick={next} className="rounded-2xl px-7 py-3 bg-white text-slate-950 font-semibold">{t.next}</button></div></section>}
  {step===4&&<section><h2 className="text-4xl font-semibold text-center">{t.step4}</h2><p className="text-slate-400 text-center mt-3">{t.step4Text}</p><div className="grid md:grid-cols-4 gap-3 mt-8">{(t.cards as string[]).map((front,i)=><button key={front} onClick={()=>setFlipped(flipped===i?null:i)} className="min-h-36 rounded-2xl border border-white/10 bg-white/[.04] p-5 text-left hover:bg-white/[.08]"><span className="text-xs uppercase tracking-wider text-slate-500">NUVYRA</span><div className="mt-3 text-sm font-medium">{flipped===i?(t.backs as string[])[i]:front}</div></button>)}</div><div className="flex justify-center mt-10"><button onClick={finish} className="rounded-2xl px-8 py-4 bg-white text-slate-950 font-semibold">{t.finish}</button></div></section>}
 </div></div>;
}
