import React, { useState } from 'react';
import { useLanguage, AppLanguage } from '../contexts/LanguageContext';

const COPY: Record<AppLanguage, any> = {
  English:{welcome:'Welcome to NUVYRA',headline:'Your body has patterns.',sub:'NUVYRA helps you notice them.',intro:'We use everyday signals such as voice, facial movement, eye activity and movement to learn your own patterns over time.',explore:"Let's explore →",works:'HOW IT WORKS',signals:'The signals we look at',tap:'Tap a card to learn more',continue:'Continue →',important:'The important part',compare:"We don't compare you",everyone:'to everyone else.',baseline:'Your personal baseline',baselineText:'NUVYRA learns what is usual for you. As you continue checking in, it looks for meaningful changes from your own pattern.',see:'See how it works →',picture:'A few signals.',clear:'One clearer picture.',flow:'Measure → Check quality → Learn your baseline → Understand change',flowText:'NUVYRA combines available signals with AI and explains the result in everyday language. It is a monitoring and research system, not a diagnosis.',start:'Start using NUVYRA ✦',skip:'Skip tour',next:'Next',cards:'NUVYRA quick guide',cardHint:'Tap a card to flip it.',fronts:['What is NUVYRA?','What is a baseline?','What does the camera do?','Is NUVYRA a diagnosis?'],backs:['A longitudinal health-technology prototype that organizes repeated observations.','Your own usual pattern, learned from repeated measurements over time.','It estimates visible motion signals such as facial, eye, breathing and movement proxies.','No. It surfaces observations and changes for review; it does not diagnose conditions.']},
  Hindi:{welcome:'NUVYRA में आपका स्वागत है',headline:'आपके शरीर के अपने पैटर्न होते हैं।',sub:'NUVYRA आपको उन्हें समझने में मदद करता है।',intro:'हम आवाज़, चेहरे की गति, आँखों की गतिविधि और मूवमेंट जैसे रोज़मर्रा के संकेतों से समय के साथ आपके अपने पैटर्न समझते हैं।',explore:'आइए शुरू करें →',works:'यह कैसे काम करता है',signals:'हम किन संकेतों को देखते हैं',tap:'जानने के लिए कार्ड दबाएँ',continue:'जारी रखें →',important:'सबसे महत्वपूर्ण बात',compare:'हम आपकी तुलना',everyone:'दूसरे लोगों से नहीं करते।',baseline:'आपकी व्यक्तिगत बेसलाइन',baselineText:'NUVYRA बार-बार के चेक-इन से आपके सामान्य पैटर्न को समझता है और उसी में बदलावों को देखता है।',see:'आगे देखें →',picture:'कुछ संकेत।',clear:'एक स्पष्ट तस्वीर।',flow:'मापें → गुणवत्ता जाँचें → बेसलाइन सीखें → बदलाव समझें',flowText:'NUVYRA उपलब्ध संकेतों को AI के साथ जोड़ता है और परिणाम सरल भाषा में समझाता है। यह मॉनिटरिंग और रिसर्च सिस्टम है, निदान नहीं।',start:'NUVYRA शुरू करें ✦',skip:'टूर छोड़ें',next:'अगला',cards:'NUVYRA क्विक गाइड',cardHint:'पलटने के लिए कार्ड दबाएँ।',fronts:['NUVYRA क्या है?','बेसलाइन क्या है?','कैमरा क्या करता है?','क्या NUVYRA निदान करता है?'],backs:['बार-बार के स्वास्थ्य-संबंधी अवलोकनों को व्यवस्थित करने वाला हेल्थ-टेक प्रोटोटाइप।','समय के साथ बार-बार के मापों से सीखा गया आपका अपना सामान्य पैटर्न।','चेहरे, आँखों, श्वास और मूवमेंट के दृश्य संकेतों का अनुमान लगाता है।','नहीं। यह बदलावों को समीक्षा के लिए दिखाता है; किसी बीमारी का निदान नहीं करता।']},
  French:{welcome:'Bienvenue sur NUVYRA',headline:'Votre corps a ses propres habitudes.',sub:'NUVYRA vous aide à les observer.',intro:'Nous utilisons des signaux du quotidien comme la voix, les mouvements du visage, les yeux et le mouvement pour apprendre vos propres habitudes.',explore:'Découvrir →',works:'COMMENT ÇA MARCHE',signals:'Les signaux observés',tap:'Touchez une carte pour en savoir plus',continue:'Continuer →',important:'Le point essentiel',compare:'Nous ne vous comparons pas',everyone:'aux autres.',baseline:'Votre baseline personnelle',baselineText:'NUVYRA apprend votre fonctionnement habituel grâce aux contrôles répétés et recherche les changements par rapport à votre propre profil.',see:'Voir le fonctionnement →',picture:'Quelques signaux.',clear:'Une image plus claire.',flow:'Mesurer → Vérifier → Apprendre votre baseline → Comprendre le changement',flowText:'NUVYRA combine les signaux disponibles avec l’IA et explique le résultat en langage courant. C’est un système de suivi et de recherche, pas un diagnostic.',start:'Commencer avec NUVYRA ✦',skip:'Passer le guide',next:'Suivant',cards:'Guide rapide NUVYRA',cardHint:'Touchez une carte pour la retourner.',fronts:['Qu’est-ce que NUVYRA ?','Qu’est-ce qu’une baseline ?','Que fait la caméra ?','NUVYRA établit-il un diagnostic ?'],backs:['Un prototype de technologie de santé qui organise des observations répétées dans le temps.','Votre propre fonctionnement habituel appris à partir de mesures répétées.','Elle estime des signaux visibles du visage, des yeux, de la respiration et du mouvement.','Non. Il présente des observations et changements pour revue, sans diagnostiquer.']}
};
const streams: Record<AppLanguage,string[][]> = {
 English:[['🎙️','Voice & speech','We look at characteristics of how you normally speak and watch for changes over time.'],['🙂','Facial dynamics','We observe natural facial movement during the camera check.'],['👁️','Eyes & blinking','The camera estimates blinking and eye-opening patterns.'],['🚶','Movement & gait','We look at visible movement patterns during the check-in.'],['🌬️','Breathing pattern','We may estimate visible rhythmic changes related to breathing.'],['🧭','Head movement','We measure visible changes in head position and movement.']],
 Hindi:[['🎙️','आवाज़ और बोलना','हम आपकी सामान्य बोलने की विशेषताओं को देखते हैं और समय के साथ बदलाव देखते हैं।'],['🙂','चेहरे की गति','कैमरा चेक में चेहरे की प्राकृतिक गति देखी जाती है।'],['👁️','आँखें और पलकें','कैमरा पलक झपकने और आँख खुलने के पैटर्न का अनुमान लगाता है।'],['🚶','मूवमेंट और चाल','चेक-इन के दौरान दिखाई देने वाले मूवमेंट पैटर्न देखे जाते हैं।'],['🌬️','श्वास पैटर्न','दिखाई देने वाली लयबद्ध श्वास-संबंधी गति का अनुमान लगाया जा सकता है।'],['🧭','सिर की गति','सिर की दिखाई देने वाली स्थिति और गति में बदलाव मापे जाते हैं।']],
 French:[['🎙️','Voix et parole','Nous observons les caractéristiques de votre façon habituelle de parler et leurs changements.'],['🙂','Dynamique du visage','Nous observons les mouvements naturels du visage pendant le contrôle caméra.'],['👁️','Yeux et clignements','La caméra estime les habitudes de clignement et d’ouverture des yeux.'],['🚶','Mouvement et marche','Nous observons les mouvements visibles pendant le contrôle.'],['🌬️','Respiration','Nous pouvons estimer certains changements rythmiques visibles liés à la respiration.'],['🧭','Mouvement de la tête','Nous mesurons les changements visibles de position et de mouvement de la tête.']]
};
export default function NuvyraWelcome({ onComplete }: { onComplete: () => void }) {
  const {language}=useLanguage(); const t=COPY[language]; const [step,setStep]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [flipped,setFlipped]=useState<number|null>(null);
  const next=()=>step<3?setStep(step+1):onComplete();
  return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center p-6">
    <div className="w-full max-w-5xl">
      {step===0&&<section className="text-center py-12"><div className="text-7xl mb-8">✦</div><p className="uppercase tracking-[0.3em] text-sm text-slate-400 mb-4">{t.welcome}</p><h1 className="text-5xl md:text-7xl font-semibold tracking-tight">{t.headline}<br/><span className="text-slate-400">{t.sub}</span></h1><p className="max-w-2xl mx-auto text-lg text-slate-300 mt-8">{t.intro}</p><div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-3">{t.fronts.map((front:string,i:number)=><button key={front} onClick={()=>setFlipped(flipped===i?null:i)} className="min-h-28 rounded-2xl border border-white/10 bg-white/[.04] p-4 text-left hover:bg-white/[.08]"><div className="text-sm font-medium">{flipped===i?t.backs[i]:front}</div></button>)}</div><p className="text-xs text-slate-500 mt-3">{t.cardHint}</p><div className="flex justify-center gap-3 mt-8"><button onClick={next} className="rounded-2xl px-7 py-4 bg-white text-slate-950 font-medium">{t.explore}</button><button onClick={onComplete} className="rounded-2xl px-7 py-4 border border-slate-700 text-slate-300">{t.skip}</button></div></section>}
      {step===1&&<section className="py-10"><p className="text-slate-400 mb-3">{t.works}</p><h2 className="text-4xl font-semibold">{t.signals}</h2><p className="text-slate-400 mt-3">{t.tap}</p><div className="grid md:grid-cols-3 gap-4 mt-8">{streams[language].map(([icon,name,desc],i)=><button key={name} onClick={()=>setSelected(selected===i?null:i)} className="text-left rounded-3xl border border-white/10 bg-white/[.04] p-6 hover:bg-white/[.08]"><span className="text-3xl">{icon}</span><h3 className="text-lg font-medium mt-4">{name}</h3>{selected===i&&<p className="text-sm text-slate-300 mt-3 leading-6">{desc}</p>}</button>)}</div><div className="flex gap-3 mt-8"><button onClick={onComplete} className="rounded-2xl px-5 py-3 border border-slate-700 text-slate-300">{t.skip}</button><button onClick={next} className="rounded-2xl px-7 py-4 bg-white text-slate-950 font-medium">{t.continue}</button></div></section>}
      {step===2&&<section className="text-center py-14"><p className="text-slate-400 uppercase tracking-widest text-sm">{t.important}</p><h2 className="text-5xl font-semibold mt-4">{t.compare}<br/><span className="text-slate-400">{t.everyone}</span></h2><div className="max-w-2xl mx-auto mt-10 rounded-3xl border border-white/10 bg-white/[.04] p-8"><div className="text-5xl">●</div><h3 className="text-2xl mt-5">{t.baseline}</h3><p className="text-slate-300 mt-3 leading-7">{t.baselineText}</p></div><div className="flex justify-center gap-3 mt-8"><button onClick={onComplete} className="rounded-2xl px-5 py-3 border border-slate-700 text-slate-300">{t.skip}</button><button onClick={next} className="rounded-2xl px-7 py-4 bg-white text-slate-950 font-medium">{t.see}</button></div></section>}
      {step===3&&<section className="text-center py-14"><h2 className="text-5xl font-semibold">{t.picture}<br/><span className="text-slate-400">{t.clear}</span></h2><div className="flex flex-wrap justify-center items-center gap-3 my-12 text-slate-300"><span>{t.flow}</span></div><p className="max-w-xl mx-auto text-slate-300">{t.flowText}</p><button onClick={onComplete} className="mt-10 rounded-2xl px-8 py-4 bg-white text-slate-950 font-semibold">{t.start}</button></section>}
      <div className="flex justify-center gap-2 mt-4">{[0,1,2,3].map(i=><span key={i} className={`h-1.5 rounded-full transition-all ${i===step?'w-8 bg-white':'w-2 bg-white/20'}`}/>)}</div>
    </div>
  </div>;
}