import React, { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { aiService, AIAnalysisResponse } from '../services/aiService';
import { InfoButton } from '../components/common/InfoButton';
import { useLanguage, AppLanguage } from '../contexts/LanguageContext';

type Voice = { rms:number; zcr:number; pitch:number; speechActivity:number };
type Camera = Record<string,number>;
const prompts: Record<AppLanguage,string[]>={
 English:['Describe your day naturally for 20 seconds.','Tell us about one thing you did today.','Describe something you noticed today.','Tell us about your plans for tomorrow.','Describe something that made you smile today.'],
 Hindi:['अपने दिन के बारे में 20 सेकंड तक सामान्य तरीके से बताइए।','आज आपने क्या किया, उसके बारे में बताइए।','आज आपने क्या खास देखा? सामान्य तरीके से बताइए।','कल की अपनी योजना के बारे में बताइए।','आज ऐसी कौन सी बात हुई जिससे आपको खुशी हुई?'],
 French:['Décrivez naturellement votre journée pendant 20 secondes.','Parlez-nous d’une chose que vous avez faite aujourd’hui.','Décrivez quelque chose que vous avez remarqué aujourd’hui.','Décrivez naturellement vos projets pour demain.','Parlez-nous de quelque chose qui vous a fait sourire aujourd’hui.']
};
const moodMap:Record<string,number>={better:.1,same:0,different:.5,significant:1};
const observations=['Vocal strain','Motor stiffness','Tremor sensations','Facial tightness','Brain fog','Sleep disruption'];
const mean=(a:number[])=>a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);
const sd=(a:number[])=>{const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)));};

async function voiceFeatures(blob:Blob):Promise<Voice>{
 const AC=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AC)throw Error('Audio analysis is unavailable.');
 const ctx=new AC();try{const audio=await ctx.decodeAudioData(await blob.arrayBuffer());const d=audio.getChannelData(0);const step=Math.max(1,Math.floor(d.length/160000));let sum=0,cross=0,n=0,prev=0;for(let i=0;i<d.length;i+=step){const v=d[i];sum+=v*v;n++;if(i>0&&((prev<0&&v>=0)||(prev>=0&&v<0)))cross++;prev=v;}const rms=Math.sqrt(sum/Math.max(1,n)),zcr=cross/Math.max(1,n-1);const frame=Math.max(256,Math.floor(audio.sampleRate*.025)),hop=Math.max(128,Math.floor(audio.sampleRate*.01));let frames=0,active=0,pitchSum=0,pitchN=0;for(let s=0;s+frame<d.length;s+=hop){let e=0;for(let j=0;j<frame;j++)e+=d[s+j]**2;const fr=Math.sqrt(e/frame);frames++;if(fr>Math.max(rms*.35,.01)){active++;const minLag=Math.floor(audio.sampleRate/400),maxLag=Math.min(Math.floor(audio.sampleRate/70),frame-1);let bestLag=0,best=-Infinity;for(let lag=minLag;lag<=maxLag;lag++){let c=0;for(let j=0;j<frame-lag;j+=4)c+=d[s+j]*d[s+j+lag];if(c>best){best=c;bestLag=lag;}}const p=bestLag?audio.sampleRate/bestLag:0;if(p>=70&&p<=400){pitchSum+=p;pitchN++;}}}return{rms:Number(rms.toFixed(6)),zcr:Number(Math.min(1,zcr).toFixed(6)),pitch:Number((pitchN?pitchSum/pitchN:0).toFixed(2)),speechActivity:Number((frames?active/frames:0).toFixed(4))};}finally{await ctx.close();}}

function breathingProxy(samples:number[],fps:number){
 // Estimate a low-frequency periodic component from the lower-centre torso region.
 // This is explicitly a visual proxy, not a physiological respiratory measurement.
 if(samples.length<25)return null;const smooth=samples.map((_,i)=>mean(samples.slice(Math.max(0,i-3),Math.min(samples.length,i+4))));const centered=smooth.map(x=>x-mean(smooth));let bestLag=0,best=-Infinity;for(let lag=Math.max(2,Math.floor(fps*2));lag<=Math.floor(fps*10);lag++){let a=0,b=0;for(let i=lag;i<centered.length;i++){a+=centered[i]*centered[i-lag];b+=centered[i]*centered[i];}const score=a/Math.max(1,b);if(score>best){best=score;bestLag=lag;}}if(bestLag<=0||best<.08)return null;const bpm=60*fps/bestLag;if(bpm<6||bpm>30)return null;return{rate:Number(bpm.toFixed(2)),variability:Number((sd(smooth)*100).toFixed(5)),confidence:Number(Math.min(1,Math.max(0,best)).toFixed(3))};
}

export const CheckInResearchPage:React.FC=()=>{
 const navigate=useNavigate();const {language,setLanguage}=useLanguage();const [step,setStep]=useState(1);const [prompt,setPrompt]=useState(prompts[language][0]);const [mood,setMood]=useState('same');const [fatigue,setFatigue]=useState(2);const [obs,setObs]=useState<string[]>([]);const [voice,setVoice]=useState<Voice|null>(null);const [camera,setCamera]=useState<Camera|null>(null);const [recording,setRecording]=useState(false);const [seconds,setSeconds]=useState(20);const [capturing,setCapturing]=useState(false);const [result,setResult]=useState<AIAnalysisResponse|null>(null);const [error,setError]=useState('');const streamRef=useRef<MediaStream|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const videoRef=useRef<HTMLVideoElement|null>(null);const canvasRef=useRef<HTMLCanvasElement|null>(null);
 useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);
 const info=(t:string,d:string)=><InfoButton title={t}>{d}</InfoButton>;
 const pickLanguage=(l:AppLanguage)=>{setLanguage(l);const list=prompts[l];setPrompt(list[Math.floor(Math.random()*list.length)]);};
 const nextPrompt=()=>{const list=prompts[language].filter(x=>x!==prompt);setPrompt(list[Math.floor(Math.random()*list.length)]||prompts[language][0]);};
 const record=async()=>{setError('');setVoice(null);try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const r=new MediaRecorder(stream,{mimeType:mime});const chunks:Blob[]=[];r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=async()=>{try{setVoice(await voiceFeatures(new Blob(chunks,{type:r.mimeType})));}catch{setError('Voice features could not be extracted from this recording.');}finally{stream.getTracks().forEach(t=>t.stop());streamRef.current=null;setRecording(false);}};recorderRef.current=r;r.start(250);setRecording(true);const start=performance.now();const timer=window.setInterval(()=>{const left=Math.max(0,Math.ceil(20-(performance.now()-start)/1000));setSeconds(left);if(!left)window.clearInterval(timer);},250);window.setTimeout(()=>{window.clearInterval(timer);if(r.state!=='inactive')r.stop();},20000);}catch{setError('Microphone access was unavailable. You can continue without voice data.');setRecording(false);}};
 const capture=async()=>{setError('');setCapturing(true);try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480,facingMode:'user'},audio:false});streamRef.current=stream;if(!videoRef.current||!canvasRef.current)throw Error('Camera preview is unavailable.');videoRef.current.srcObject=stream;await videoRef.current.play();const canvas=canvasRef.current;canvas.width=160;canvas.height=120;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw Error('Camera analysis is unavailable.');const motion:number[]=[],lum:number[]=[],eye:number[]=[],head:number[]=[],breath:number[]=[];let prev:Uint8ClampedArray|null=null;const start=performance.now(),fps=5;while(performance.now()-start<10000){ctx.drawImage(videoRef.current,0,0,160,120);const p=ctx.getImageData(0,0,160,120).data;let l=0,diff=0,top=0,bottom=0,left=0,right=0,lower=0,lowerN=0;for(let i=0;i<p.length;i+=4){const x=(i/4)%160,y=Math.floor((i/4)/160),v=.2126*p[i]+.7152*p[i+1]+.0722*p[i+2];l+=v;if(y<45)top+=v;if(y>75)bottom+=v;if(x<55)left+=v;if(x>105)right+=v;if(y>65&&x>35&&x<125){lower+=v;lowerN++;}if(prev)diff+=Math.abs(v-(.2126*prev[i]+.7152*prev[i+1]+.0722*prev[i+2]));}motion.push(diff/(160*120*255));lum.push(l/(160*120*255));eye.push(Math.abs(top-bottom)/(160*120*255));head.push(Math.abs(left-right)/(160*120*255));breath.push(lower/Math.max(1,lowerN)/255);prev=new Uint8ClampedArray(p);await new Promise(r=>setTimeout(r,200));}const b=breathingProxy(breath,fps);const movement=mean(motion);const cameraQuality=1-Math.min(1,sd(motion)*8);const out:Camera={face_motion:Number(movement.toFixed(6)),face_luminance_variability:Number(sd(lum).toFixed(6)),face_blink_proxy:Number(Math.min(1,mean(eye)*10).toFixed(4)),blink_rate_per_minute:Number(Math.min(60,mean(eye)*60).toFixed(2)),eye_opening_proxy:Number(Math.max(0,Math.min(1,1-mean(eye)*10)).toFixed(4)),gait_motion:Number(movement.toFixed(6)),gait_variability:Number(sd(motion).toFixed(6)),gait_symmetry_proxy:Number(Math.max(0,Math.min(1,1-sd(head)*10)).toFixed(4)),head_motion:Number(mean(head).toFixed(6)),head_motion_variability:Number(sd(head).toFixed(6))};if(b){out.breathing_rate_per_minute=b.rate;out.breathing_variability=b.variability;}if(cameraQuality<.25)throw Error('The camera signal was too noisy. Please improve lighting and keep the camera steady, then try again.');setCamera(out);}catch(e:any){setError(e?.message||'Camera analysis was unavailable.');}finally{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCapturing(false);}};
 const analyze=async()=>{setError('');try{const r=await aiService.analyze({fatigue,mood_deviation:moodMap[mood]??0,symptom_burden:obs.length/observations.length,voice_language:language,...(voice?{voice_rms:voice.rms,voice_zero_crossing_rate:voice.zcr,voice_pitch_hz:voice.pitch,voice_speech_activity:voice.speechActivity}:{}),...(camera||{}),source_duration_seconds:voice?20:0});setResult(r);}catch(e:any){if(e?.status===401)navigate('/login');else setError(e?.message||'AI analysis failed.');}};
 const toggle=(x:string)=>setObs(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 const help={voice:'Voice features describe sound characteristics such as pitch and speech activity. They are research measurements, not a clinical speech assessment.',camera:'Camera features are computer-vision proxies. Face the camera, keep your full face and upper torso visible, use even lighting, keep the camera steady, blink naturally and do not deliberately change your expression.',breathing:'Breathing rhythm is estimated from low-frequency visual changes in the lower-centre video area. It is a research proxy, not a medical breathing measurement. Breathe normally.',quality:'NUVYRA checks whether signals are finite, sufficiently complete and reasonably stable. Noisy or missing modalities are excluded rather than treated as normal.',baseline:'NUVYRA compares measurements mainly with your own previous usable observations. One unusual session is not treated as a diagnosis.',ai:'The research AI combines usable modalities, checks quality, compares personal baselines and looks for changes that persist across sessions.'};
 return <main className="mx-auto max-w-4xl space-y-6 py-5 text-white"><div className="flex justify-between text-xs text-slate-500"><span>DAILY MULTIMODAL CHECK-IN · {step}/4</span><span>PERSONAL BASELINE</span></div>{error&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200">{error}</div>}
 {step===1&&<section className="rounded-2xl border border-slate-800 bg-[#111827] p-6 space-y-5"><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold">How are you today?</h1>{info('About this step','These answers are optional personal context. They are not a diagnosis.')}</div><div className="grid grid-cols-2 gap-3">{Object.entries({better:'Better than usual',same:'About the same',different:'A little different',significant:'Noticeably different'}).map(([k,v])=><button key={k} onClick={()=>setMood(k)} className={`rounded-xl border p-3 text-left ${mood===k?'border-sky-400 bg-sky-500/10':'border-slate-800 bg-slate-900'}`}>{v}</button>)}</div><label className="block text-sm text-slate-300">Fatigue: {fatigue}/10<input className="mt-2 w-full" type="range" min="0" max="10" value={fatigue} onChange={e=>setFatigue(Number(e.target.value))}/></label><div><p className="mb-2 text-sm text-slate-300">Anything you noticed? <span className="text-slate-500">optional</span></p><div className="flex flex-wrap gap-2">{observations.map(x=><button key={x} onClick={()=>toggle(x)} className={`rounded-lg border px-3 py-2 text-xs ${obs.includes(x)?'border-teal-400 bg-teal-500/10':'border-slate-800'}`}>{obs.includes(x)?'✓ ':''}{x}</button>)}</div></div><button onClick={()=>setStep(2)} className="w-full rounded-xl bg-white py-3 font-semibold text-slate-950">Continue</button></section>}
 {step===2&&<section className="rounded-2xl border border-slate-800 bg-[#111827] p-6 space-y-5"><div className="flex items-center gap-2"><h2 className="text-2xl font-semibold">Voice & speech</h2>{info('What we measure',help.voice)}</div><div className="grid grid-cols-3 gap-2">{(['English','Hindi','French'] as AppLanguage[]).map(l=><button key={l} onClick={()=>pickLanguage(l)} className={`rounded-xl border py-2 ${language===l?'bg-white text-slate-950':'border-slate-700'}`}>{l==='Hindi'?'हिन्दी':l==='French'?'Français':l}</button>)}</div><div className="rounded-xl bg-slate-900 p-5"><p className="text-xs uppercase text-slate-500">Read / speak naturally</p><p className="mt-2 leading-7">{prompt}</p><button onClick={nextPrompt} className="mt-3 text-sm text-sky-300 underline">Different prompt</button></div><p className="rounded-xl border border-slate-800 p-4 text-sm text-slate-400">Speak naturally for the full <b className="text-white">20 seconds</b>. Quiet room, comfortable pace, no deliberate voice changes.</p><button disabled={recording} onClick={record} className="mx-auto block rounded-xl bg-sky-400 px-6 py-3 font-semibold text-slate-950">{recording?`Recording… ${seconds}s`:voice?'✓ 20-second sample captured':'Record 20-second sample'}</button>{voice&&<div className="grid grid-cols-2 md:grid-cols-4 gap-2">{[['Pitch',`${voice.pitch} Hz`],['Sound strength',voice.rms.toFixed(4)],['Sound pattern',voice.zcr.toFixed(3)],['Speech activity',`${Math.round(voice.speechActivity*100)}%`]].map(([k,v])=><div key={k} className="rounded-xl bg-slate-900 p-3 text-center text-xs"><span>{k}</span><b className="mt-1 block text-white">{v}</b></div>)}</div>}<button disabled={!voice} onClick={()=>setStep(3)} className="w-full rounded-xl bg-teal-400 py-3 font-semibold text-slate-950 disabled:opacity-40">Continue to camera</button></section>}
 {step===3&&<section className="rounded-2xl border border-slate-800 bg-[#111827] p-6 space-y-5"><div className="flex items-center gap-2"><h2 className="text-2xl font-semibold">Face, movement & breathing</h2>{info('Camera instructions',help.camera)}</div><p className="rounded-xl border border-slate-800 p-4 text-sm leading-6 text-slate-400">Keep your face and upper torso visible. Use even front lighting. Keep the camera steady. Blink and breathe normally. The system estimates breathing from visible low-frequency motion and may omit it when the signal is too noisy. {info('Breathing',help.breathing)}</p><video ref={videoRef} muted playsInline className="mx-auto aspect-video w-full max-w-md rounded-xl bg-black object-cover scale-x-[-1]"/><canvas ref={canvasRef} className="hidden"/><button disabled={capturing} onClick={capture} className="mx-auto block rounded-xl bg-teal-400 px-6 py-3 font-semibold text-slate-950">{capturing?'Checking camera…':camera?'✓ Camera sample captured':'Start 10-second camera sample'}</button>{camera&&<div className="grid grid-cols-2 md:grid-cols-3 gap-2">{Object.entries(camera).map(([k,v])=><div key={k} className="rounded-xl bg-slate-900 p-3 text-xs"><div className="text-slate-400">{k.replaceAll('_',' ')}</div><b className="mt-1 block text-white">{v}</b></div>)}</div>}<button disabled={!camera} onClick={()=>setStep(4)} className="w-full rounded-xl bg-sky-400 py-3 font-semibold text-slate-950 disabled:opacity-40">Review AI analysis</button></section>}
 {step===4&&<section className="rounded-2xl border border-slate-800 bg-[#111827] p-6 space-y-5"><div className="flex items-center gap-2"><h2 className="text-2xl font-semibold">Multimodal AI assessment</h2>{info('How this works',`${help.ai} ${help.quality} ${help.baseline}`)}</div>{!result?<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Voice',!!voice],['Camera',!!camera],['Breathing',!!camera&&camera.breathing_rate_per_minute!==undefined],['Personal baseline',true]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-slate-900 p-4"><div className="text-sm">{k}</div><div className={`mt-2 text-xs ${v?'text-emerald-300':'text-slate-500'}`}>{v?'Available':'Unavailable — excluded'}</div></div>)}</div><button onClick={analyze} className="w-full rounded-xl bg-white py-3 font-semibold text-slate-950">Run NUVYRA research AI</button></>:<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Pattern',result.overall_score.toFixed(1)],['Confidence',`${Math.round(result.confidence*100)}%`],['Data quality',`${Math.round(result.data_quality_score*100)}%`],['Persistence',result.persistence_signal]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-slate-900 p-4"><div className="text-xs text-slate-400">{k}</div><b className="mt-2 block">{v}</b></div>)}</div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold">What the AI noticed</h3><p className="mt-2 text-sm leading-6 text-slate-300">{result.explanation}</p></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold">Missing signals</h3><p className="mt-2 text-sm text-slate-400">{result.missing_modalities?.length?result.missing_modalities.join(', '):'None'}</p></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold">Research limitations</h3><ul className="mt-2 space-y-1 text-xs text-slate-500">{result.limitations.map(x=><li key={x}>• {x}</li>)}</ul></div><button onClick={()=>navigate('/trends')} className="w-full rounded-xl bg-sky-400 py-3 font-semibold text-slate-950">View history</button></>}</section>}
 </main>;
};
