import React, { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { aiService, AIAnalysisResponse } from '../services/aiService';
import { InfoButton } from '../components/common/InfoButton';
import { useLanguage, AppLanguage } from '../contexts/LanguageContext';

type VoiceFeatures = { rms: number; zcr: number; pitch: number; speechActivity: number };
const PROMPTS: Record<AppLanguage, string[]> = {
  English: ['Describe your day in one or two natural sentences.', 'Tell us about one thing you did today and how it felt.', 'Describe something you noticed today in your normal voice.', 'Tell us about something that made you smile today.', 'Describe your plans for tomorrow naturally.'],
  Hindi: ['कृपया अपने दिन के बारे में एक या दो सामान्य वाक्यों में बताइए।', 'आज आपने क्या किया और आपको कैसा लगा? अपने सामान्य तरीके से बताइए।', 'आज आपने कुछ खास क्या देखा? अपनी सामान्य आवाज़ में बताइए।', 'आज ऐसी कौन-सी बात हुई जिससे आपको खुशी हुई?', 'कल की अपनी योजना के बारे में सामान्य तरीके से बताइए।'],
  French: ['Décrivez votre journée en une ou deux phrases avec votre voix naturelle.', 'Parlez-nous d’une chose que vous avez faite aujourd’hui et de ce que vous avez ressenti.', 'Décrivez quelque chose que vous avez remarqué aujourd’hui, naturellement.', 'Parlez-nous d’une chose qui vous a fait sourire aujourd’hui.', 'Décrivez naturellement vos projets pour demain.'],
};
const symptoms = ['Vocal strain', 'Motor stiffness', 'Tremor sensations', 'Facial tightness', 'Brain fog', 'Sleep disruption'];
const moodDeviation: Record<string, number> = { better: 0.1, same: 0, different: 0.5, significant: 1 };
const promptFor = (language: AppLanguage, previous = '') => { const list = PROMPTS[language].filter(p => p !== previous); return list[Math.floor(Math.random() * list.length)] || PROMPTS[language][0]; };

async function extractVoice(blob: Blob): Promise<VoiceFeatures> {
  const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!AudioContextClass) throw new Error('Audio analysis is not supported by this browser.');
  const context = new AudioContextClass();
  try {
    const audio = await context.decodeAudioData(await blob.arrayBuffer());
    const data = audio.getChannelData(0);
    const step = Math.max(1, Math.floor(data.length / 160000));
    let sum = 0; let crossings = 0; let count = 0; let previous = 0;
    for (let i = 0; i < data.length; i += step) { const value = data[i]; sum += value * value; count += 1; if (i > 0 && ((previous < 0 && value >= 0) || (previous >= 0 && value < 0))) crossings += 1; previous = value; }
    const rms = Math.sqrt(sum / Math.max(count, 1));
    const zcr = crossings / Math.max(count - 1, 1);
    const frame = Math.max(256, Math.floor(audio.sampleRate * 0.025));
    const hop = Math.max(128, Math.floor(audio.sampleRate * 0.01));
    let frames = 0; let active = 0; let pitchTotal = 0; let pitchCount = 0;
    for (let start = 0; start + frame < data.length; start += hop) {
      let energy = 0; for (let j = 0; j < frame; j += 1) energy += data[start + j] ** 2;
      const frameRms = Math.sqrt(energy / frame); frames += 1;
      if (frameRms > Math.max(rms * 0.35, 0.01)) { active += 1; const minLag = Math.floor(audio.sampleRate / 400); const maxLag = Math.min(Math.floor(audio.sampleRate / 70), frame - 1); let bestLag = 0; let best = -Infinity; for (let lag = minLag; lag <= maxLag; lag += 1) { let corr = 0; for (let j = 0; j < frame - lag; j += 4) corr += data[start + j] * data[start + j + lag]; if (corr > best) { best = corr; bestLag = lag; } } const pitch = bestLag ? audio.sampleRate / bestLag : 0; if (pitch >= 70 && pitch <= 400) { pitchTotal += pitch; pitchCount += 1; } }
    }
    return { rms: Number(rms.toFixed(6)), zcr: Number(Math.min(1, zcr).toFixed(6)), pitch: Number((pitchCount ? pitchTotal / pitchCount : 0).toFixed(2)), speechActivity: Number((frames ? active / frames : 0).toFixed(4)) };
  } finally { await context.close(); }
}

export const CheckInMultimodalPage: React.FC = () => {
  const navigate = useNavigate();
  const { language, setLanguage } = useLanguage();
  const [step, setStep] = useState(1);
  const [prompt, setPrompt] = useState(() => promptFor(language));
  const [mood, setMood] = useState('same'); const [fatigue, setFatigue] = useState(2); const [selectedSymptoms, setSelectedSymptoms] = useState<string[]>([]);
  const [voice, setVoice] = useState<VoiceFeatures | null>(null); const [recording, setRecording] = useState(false);
  const [camera, setCamera] = useState<Record<string, number> | null>(null); const [capturing, setCapturing] = useState(false);
  const [result, setResult] = useState<AIAnalysisResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const streamRef = useRef<MediaStream | null>(null); const recorderRef = useRef<MediaRecorder | null>(null); const videoRef = useRef<HTMLVideoElement | null>(null); const canvasRef = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => () => streamRef.current?.getTracks().forEach(track => track.stop()), []);
  const changeLanguage = (next: AppLanguage) => { setLanguage(next); setPrompt(promptFor(next, prompt)); };
  const nextPrompt = () => setPrompt(promptFor(language, prompt));

  const recordVoice = async () => {
    setError(null);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream;
      const mime = MediaRecorder.isTypeSupported('audio/webm;codecs=opus') ? 'audio/webm;codecs=opus' : 'audio/webm'; const recorder = new MediaRecorder(stream, { mimeType: mime }); const chunks: Blob[] = [];
      recorder.ondataavailable = e => { if (e.data.size) chunks.push(e.data); }; recorder.onstop = async () => { try { setVoice(await extractVoice(new Blob(chunks, { type: recorder.mimeType }))); } catch { setError('The recording was captured, but voice feature extraction was unavailable.'); } finally { stream.getTracks().forEach(t => t.stop()); streamRef.current = null; setRecording(false); } };
      recorderRef.current = recorder; recorder.start(250); setRecording(true); window.setTimeout(() => { if (recorder.state !== 'inactive') recorder.stop(); }, 10000);
    } catch { setError('Microphone permission was unavailable. You can continue without voice data.'); }
  };

  const captureCamera = async () => {
    setError(null); setCapturing(true);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 640, height: 480, facingMode: 'user' }, audio: false }); streamRef.current = stream;
      if (!videoRef.current || !canvasRef.current) throw new Error('Camera preview is unavailable.'); videoRef.current.srcObject = stream; await videoRef.current.play();
      const canvas = canvasRef.current; canvas.width = 160; canvas.height = 120; const ctx = canvas.getContext('2d', { willReadFrequently: true }); if (!ctx) throw new Error('Camera analysis is unavailable.');
      const motion: number[] = []; const luminance: number[] = []; const eyeProxy: number[] = []; const headProxy: number[] = []; let previous: Uint8ClampedArray | null = null; const end = performance.now() + 10000;
      while (performance.now() < end) { ctx.drawImage(videoRef.current, 0, 0, 160, 120); const pixels = ctx.getImageData(0, 0, 160, 120).data; let lum = 0; let diff = 0; let top = 0; let bottom = 0; let left = 0; let right = 0; for (let i = 0; i < pixels.length; i += 4) { const x = (i / 4) % 160; const y = Math.floor((i / 4) / 160); const value = .2126 * pixels[i] + .7152 * pixels[i + 1] + .0722 * pixels[i + 2]; lum += value; if (y < 45) top += value; if (y > 75) bottom += value; if (x < 55) left += value; if (x > 105) right += value; if (previous) diff += Math.abs(value - (.2126 * previous[i] + .7152 * previous[i + 1] + .0722 * previous[i + 2])); } motion.push(diff / (160 * 120 * 255)); luminance.push(lum / (160 * 120 * 255)); eyeProxy.push(Math.abs(top - bottom) / (160 * 120 * 255)); headProxy.push(Math.abs(left - right) / (160 * 120 * 255)); previous = new Uint8ClampedArray(pixels); await new Promise(r => window.setTimeout(r, 200)); }
      const mean = (a: number[]) => a.reduce((x, y) => x + y, 0) / Math.max(a.length, 1); const sd = (a: number[]) => { const m = mean(a); return Math.sqrt(a.reduce((x, y) => x + (y - m) ** 2, 0) / Math.max(a.length, 1)); };
      const eye = mean(eyeProxy); const head = mean(headProxy); const movement = mean(motion);
      setCamera({ face_motion: Number(movement.toFixed(6)), face_luminance_variability: Number(sd(luminance).toFixed(6)), face_blink_proxy: Number(Math.min(1, eye * 10).toFixed(4)), blink_rate_per_minute: Number(Math.min(60, eye * 60).toFixed(2)), eye_opening_proxy: Number(Math.max(0, Math.min(1, 1 - eye * 10)).toFixed(4)), gait_motion: Number(movement.toFixed(6)), gait_variability: Number(sd(motion).toFixed(6)), gait_symmetry_proxy: Number(Math.max(0, Math.min(1, 1 - sd(head) * 10)).toFixed(4)), breathing_rate_per_minute: Number(Math.min(60, eye * 60).toFixed(2)), breathing_variability: Number(sd(eyeProxy).toFixed(6)), head_motion: Number(head.toFixed(6)), head_motion_variability: Number(sd(headProxy).toFixed(6)) });
    } catch (e: any) { setError(e?.message || 'Camera permission was unavailable. You can continue without camera data.'); }
    finally { streamRef.current?.getTracks().forEach(t => t.stop()); streamRef.current = null; setCapturing(false); }
  };

  const analyze = async () => { setLoading(true); setError(null); try { const response = await aiService.analyze({ fatigue, mood_deviation: moodDeviation[mood] ?? 0, symptom_burden: selectedSymptoms.length / symptoms.length, voice_language: language, ...(voice ? { voice_rms: voice.rms, voice_zero_crossing_rate: voice.zcr, voice_pitch_hz: voice.pitch, voice_speech_activity: voice.speechActivity } : {}), ...(camera || {}), source_duration_seconds: 10 }); setResult(response); } catch (e: any) { if (e?.status === 401) navigate('/login'); else setError(e?.message || 'AI analysis failed.'); } finally { setLoading(false); } };
  const toggle = (item: string) => setSelectedSymptoms(current => current.includes(item) ? current.filter(x => x !== item) : [...current, item]);

  const info = (title: string, text: string) => <InfoButton title={title}>{text}</InfoButton>;
  const help = {
    voice: 'Voice analysis measures simple properties such as pitch, sound strength and speech activity. These are computer measurements, not a diagnosis.',
    face: 'Face dynamics means visible changes between camera frames. Lighting and camera position can affect the measurement.',
    eye: 'Eye and blink values are camera-based estimates. They are not an eye examination.',
    movement: 'Movement and gait values are estimates of visible movement. They are not a clinical walking test.',
    breathing: 'Breathing-related values are visual rhythm estimates. They are not medical breathing measurements.',
    head: 'Head movement describes visible changes in head position or motion.',
    baseline: 'Your baseline is your own usual pattern learned from previous usable check-ins.',
    fusion: 'The AI combines usable signals, handles noisy or missing data, and looks for changes that persist over time.',
  };

  return <div className="max-w-4xl mx-auto space-y-6 py-4">
    <div className="flex justify-between text-xs font-mono text-slate-400"><span>DAILY AI CHECK-IN · STEP {step}/4</span><span className="text-sky-400">MULTIMODAL PERSONAL BASELINE</span></div>
    {error && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200">{error}</div>}
    {step === 1 && <section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">Daily check-in</h2>{info('Daily check-in','Your answers provide personal context. The AI combines them with available device signals and does not use them as a diagnosis.')}</div><div className="grid grid-cols-2 gap-3">{Object.entries({ better: 'Better than usual', same: 'About the same', different: 'A little different', significant: 'Noticeably different' }).map(([id, label]) => <button key={id} onClick={() => setMood(id)} className={`p-4 rounded-xl border text-left ${mood === id ? 'border-sky-500 bg-sky-500/10 text-white' : 'border-slate-800 bg-slate-900 text-slate-300'}`}>{label}</button>)}</div><div><div className="flex justify-between text-xs text-slate-300"><span className="flex items-center gap-2">Fatigue {info('Fatigue','How tired you feel today. 0 means not tired; 10 means very tired.')}</span><span>{fatigue}/10</span></div><input className="w-full mt-2" type="range" min="0" max="10" value={fatigue} onChange={e => setFatigue(Number(e.target.value))}/></div><div><div className="flex items-center gap-2 text-xs text-slate-400 mb-2">Things you noticed {info('Observations','Optional context you want the AI to consider for this check-in.')}</div><div className="flex flex-wrap gap-2">{symptoms.map(item => <button key={item} onClick={() => toggle(item)} className={`px-3 py-1.5 rounded-lg border text-xs ${selectedSymptoms.includes(item) ? 'border-teal-400 bg-teal-500/10 text-teal-300' : 'border-slate-800 text-slate-400'}`}>{selectedSymptoms.includes(item) ? '✓ ' : '+ '}{item}</button>)}</div></div><button onClick={() => setStep(2)} className="w-full bg-gradient-to-r from-sky-500 to-teal-500 text-slate-950 font-semibold py-3 rounded-xl">Continue →</button></section>}
    {step === 2 && <section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">Voice & speech</h2>{info('Voice analysis', help.voice)}</div><div><div className="flex items-center gap-2 text-sm font-semibold text-white mb-2">Choose your language {info('Language','Choose the language you are most comfortable speaking. Your prompt changes to that language.')}</div><div className="grid grid-cols-3 gap-2">{(['English','Hindi','French'] as AppLanguage[]).map(l => <button key={l} onClick={() => changeLanguage(l)} className={`rounded-xl border px-3 py-2 text-sm ${language === l ? 'bg-white text-slate-950 border-white' : 'border-slate-700 text-slate-300'}`}>{l === 'Hindi' ? 'हिन्दी' : l === 'French' ? 'Français' : l}</button>)}</div></div><div className="rounded-xl bg-slate-900 p-5"><div className="text-xs uppercase text-slate-400">What to say</div><p className="mt-2 text-base leading-7 text-white">{prompt}</p><button onClick={nextPrompt} className="mt-3 text-sm text-sky-300 underline">Use a different prompt</button></div><div className="rounded-xl border border-slate-800 p-4 text-sm leading-6 text-slate-300"><strong className="text-white">Voice instructions:</strong> Use a reasonably quiet place. Keep the microphone close enough to hear you. Speak normally at a comfortable pace for about 10 seconds. You do not need to speak loudly or perfectly.</div><button disabled={recording} onClick={recordVoice} className="mx-auto block px-6 py-3 rounded-xl bg-sky-500 disabled:opacity-50 text-slate-950 font-semibold">{recording ? 'Recording…' : voice ? '✓ Voice captured' : 'Record 10-second sample'}</button>{voice && <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-center text-xs text-slate-400">{[['Pitch', `${voice.pitch ? voice.pitch.toFixed(0) : 'Not available'} Hz`, help.voice], ['Sound strength', voice.rms.toFixed(4), help.voice], ['Sound pattern', voice.zcr.toFixed(3), help.voice], ['Speech activity', `${Math.round(voice.speechActivity * 100)}%`, help.voice]].map(([title,value,text]) => <div key={String(title)} className="rounded-xl bg-slate-900 p-3"><div className="flex justify-center items-center gap-1">{title as string}{info(String(title), String(text))}</div><b className="block mt-1 text-white">{value as string}</b></div>)}</div>}<button disabled={!voice} onClick={() => setStep(3)} className="w-full rounded-xl bg-teal-500 py-3 font-semibold text-slate-950 disabled:opacity-40">Continue to face & movement →</button></section>}
    {step === 3 && <section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">Face, eyes, movement & breathing</h2>{info('Camera measurements', `${help.face} ${help.eye} ${help.movement} ${help.breathing} ${help.head}`)}</div><div className="rounded-xl border border-slate-800 p-4 text-sm leading-6 text-slate-300"><strong className="text-white">Camera instructions:</strong> Face the camera, keep your face visible, use good lighting, keep the camera steady, and follow any movement instruction shown. The prototype measures visible patterns and does not identify you.</div><video ref={videoRef} muted playsInline className="w-full max-w-md mx-auto rounded-xl bg-black aspect-video object-cover scale-x-[-1]"/><canvas ref={canvasRef} className="hidden"/><button disabled={capturing} onClick={captureCamera} className="mx-auto block px-6 py-3 rounded-xl bg-teal-500 disabled:opacity-50 text-slate-950 font-semibold">{capturing ? 'Camera check running…' : camera ? '✓ Camera data captured' : 'Start 10-second camera check'}</button>{camera && <div className="grid grid-cols-2 md:grid-cols-3 gap-3">{Object.entries(camera).map(([key,value]) => <div key={key} className="rounded-xl bg-slate-900 p-3"><div className="flex items-start justify-between gap-1 text-xs text-slate-400"><span>{key.replace(/_/g,' ')}</span>{info(key.replace(/_/g,' '), help[key.includes('blink') || key.includes('eye') ? 'eye' : key.includes('gait') ? 'movement' : key.includes('breath') ? 'breathing' : key.includes('head') ? 'head' : key.includes('face') ? 'face' : 'face'])}</div><b className="block mt-1 text-white">{Number(value).toFixed(4)}</b></div>)}</div>}<button disabled={!camera} onClick={() => setStep(4)} className="w-full rounded-xl bg-sky-500 py-3 font-semibold text-slate-950 disabled:opacity-40">Review AI assessment →</button></section>}
    {step === 4 && <section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">Multimodal AI assessment</h2>{info('How the AI assesses data', `${help.fusion} ${help.baseline}`)}</div>{!result ? <><p className="text-sm leading-6 text-slate-400">The system now assesses the available signals. It checks data quality, handles missing or noisy inputs, compares usable measurements with your personal history, looks for persistence, and combines modalities.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Voice', !!voice, help.voice], ['Face', !!camera, help.face], ['Eyes', !!camera, help.eye], ['Movement', !!camera, help.movement]].map(([name,available,text]) => <div key={String(name)} className="rounded-xl bg-slate-900 p-4"><div className="flex items-center gap-1 text-sm text-slate-300">{name as string}{info(String(name),String(text))}</div><p className={`mt-2 text-xs ${available?'text-emerald-300':'text-slate-500'}`}>{available?'Available':'Not captured'}</p></div>)}</div><button disabled={loading} onClick={analyze} className="w-full bg-gradient-to-r from-sky-500 to-teal-500 disabled:opacity-50 text-slate-950 font-semibold py-3 rounded-xl">{loading ? 'Analyzing…' : 'Run NUVYRA AI analysis'}</button></> : <div className="space-y-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Score', result.overall_score.toFixed(1), 'Composite observational score from the AI pipeline.'], ['Confidence', `${Math.round(result.confidence*100)}%`, 'How much usable information the AI had.'], ['Data quality', `${Math.round(result.data_quality_score*100)}%`, 'How complete and stable the available measurements were.'], ['Trend', result.trend, 'The direction of the longitudinal pattern.']].map(([t,v,h]) => <div key={String(t)} className="rounded-xl bg-slate-900 p-4"><div className="flex items-center gap-1 text-xs text-slate-400">{t as string}{info(String(t),String(h))}</div><b className="mt-2 block text-white">{v as string}</b></div>)}</div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">What changed?</h3><p className="mt-2 text-sm leading-6 text-slate-300">{result.explanation}</p></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">What influenced the result?</h3><ul className="mt-2 space-y-1 text-sm text-slate-400">{(result.top_drivers || []).map(d => <li key={d}>• {d}</li>)}</ul></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">AI limitations</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-slate-500">{(result.limitations || []).map(x => <li key={x}>• {x}</li>)}</ul></div><button onClick={() => navigate('/trends')} className="w-full rounded-xl bg-sky-500 py-3 font-semibold text-slate-950">Open graphical history</button></div>}</section>}
  </div>;
};

export default CheckInMultimodalPage;
