import React, { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { aiService, AIAnalysisResponse } from '../services/aiService';
import { InfoButton } from '../components/common/InfoButton';
import { useLanguage, AppLanguage } from '../contexts/LanguageContext';

type VoiceFeatures = { rms: number; zcr: number; pitch: number; speechActivity: number };
const PROMPTS: Record<AppLanguage, string[]> = { English: ['Describe your day in one or two natural sentences.', 'Tell us about one thing you did today and how it felt.', 'Describe something you noticed today in your normal voice.', 'Tell us about something that made you smile today.', 'Describe your plans for tomorrow naturally.'], Hindi: ['कृपया अपने दिन के बारे में एक या दो सामान्य वाक्यों में बताइए।', 'आज आपने क्या किया और आपको कैसा लगा? अपने सामान्य तरीके से बताइए।', 'आज आपने कुछ खास क्या देखा? अपनी सामान्य आवाज़ में बताइए।', 'आज ऐसी कौन-सी बात हुई जिससे आपको खुशी हुई?', 'कल की अपनी योजना के बारे में सामान्य तरीके से बताइए।'], French: ['Décrivez votre journée en une ou deux phrases avec votre voix naturelle.', 'Parlez-nous d’une chose que vous avez faite aujourd’hui et de ce que vous avez ressenti.', 'Décrivez quelque chose que vous avez remarqué aujourd’hui, naturellement.', 'Parlez-nous d’une chose qui vous a fait sourire aujourd’hui.', 'Décrivez naturellement vos projets pour demain.'] };
const symptoms = ['Vocal strain', 'Motor stiffness', 'Tremor sensations', 'Facial tightness', 'Brain fog', 'Sleep disruption'];
const COPY: Record<AppLanguage, Record<string,string>> = {
  English: {
    daily:'DAILY AI CHECK-IN · STEP', baseline:'{t(language,'baseline')}', feeling:'{t(language,'feeling')}', feelingHelp:'Your answers capture your own experience and context. They are self-reported observations, not a medical or psychological assessment.', feelingIntro:'{t(language,'feelingIntro')}',
    overall:'{t(language,'overall')}', better:'{t(language,'better')}', same:'{t(language,'same')}', different:'{t(language,'different')}', significant:'{t(language,'significant')}',
    energy:'{t(language,'energy')}', sleep:'{t(language,'sleep')}', stress:'{t(language,'stress')}', concentration:'{t(language,'concentration')}', comfort:'{t(language,'comfort')}', appetite:'{t(language,'appetite')}', fatigue:'{t(language,'fatigue')}', noticed:'{t(language,'noticed')}', observed:'{t(language,'observed')}',
    continue:'{t(language,'continue')}', voice:'{t(language,'voice')}', chooseLanguage:'{t(language,'chooseLanguage')}', whatSay:'{t(language,'whatSay')}', differentPrompt:'{t(language,'differentPrompt')}', instructions:'{t(language,'instructions')}', voice{t(language,'instructions')}'{t(language,'voiceInstructions')}', record:'{t(language,'record')}', recording:'Recording…', captured:'{t(language,'captured')}', pitch:'{t(language,'pitch')}', sound:'{t(language,'sound')}', waveform:'{t(language,'waveform')}', speech:'{t(language,'speech')}', continueCamera:'{t(language,'continueCamera')}',
    cameraTitle:'{t(language,'cameraTitle')}', camera{t(language,'instructions')}'{t(language,'cameraInstructions')}', cameraStart:'{t(language,'cameraStart')}', cameraRunning:'{t(language,'cameraRunning')}', cameraCaptured:'{t(language,'cameraCaptured')}', review:'{t(language,'review')}', assessment:'{t(language,'assessment')}', assessmentText:'{t(language,'assessmentText')}', run:'{t(language,'run')}', analyzing:'{t(language,'analyzing')}', score:'{t(language,'score')}', confidence:'{t(language,'confidence')}', quality:'{t(language,'quality')}', trend:'{t(language,'trend')}', changed:'{t(language,'changed')}', influenced:'{t(language,'influenced')}', limitations:'{t(language,'limitations')}', history:'{t(language,'history')}',
    notDisease:'A change in one answer does not identify a disease or its cause.'
  },
  Hindi: {
    daily:'दैनिक AI चेक-इन · चरण', baseline:'मल्टीमॉडल व्यक्तिगत बेसलाइन', feeling:'आज आप कैसा महसूस कर रहे हैं?', feelingHelp:'आपके उत्तर आपके अनुभव और संदर्भ को बताते हैं। ये स्वयं-रिपोर्ट किए गए अवलोकन हैं, चिकित्सीय या मनोवैज्ञानिक आकलन नहीं।', feelingIntro:'यह बाद में लिए जाने वाले मापों के लिए NUVYRA को संदर्भ देता है।',
    overall:'समग्र अनुभव', better:'सामान्य से बेहतर', same:'लगभग सामान्य', different:'थोड़ा अलग', significant:'काफी अलग',
    energy:'ऊर्जा', sleep:'नींद की गुणवत्ता', stress:'तनाव', concentration:'एकाग्रता', comfort:'शारीरिक आराम', appetite:'भूख', fatigue:'थकान', noticed:'आपने क्या महसूस किया?', observed:'इस चेक-इन के संदर्भ के रूप में AI को बताने के लिए वैकल्पिक जानकारी।',
    continue:'जारी रखें →', voice:'आवाज़ और बोलना', chooseLanguage:'अपनी भाषा चुनें', whatSay:'क्या बोलें', differentPrompt:'दूसरा प्रॉम्प्ट चुनें', instructions:'निर्देश:', voice{t(language,'instructions')}'शांत जगह चुनें, माइक्रोफ़ोन से पर्याप्त दूरी रखें और 20 सेकंड तक स्वाभाविक रूप से बोलें। अपनी आवाज़ या पिच को जानबूझकर न बदलें।', record:'20 सेकंड का नमूना रिकॉर्ड करें', recording:'रिकॉर्ड हो रहा है…', captured:'✓ आवाज़ रिकॉर्ड हुई', pitch:'पिच', sound:'ध्वनि की तीव्रता', waveform:'वेवफॉर्म विशेषता', speech:'बोलने की गतिविधि', continueCamera:'चेहरे और मूवमेंट पर जाएँ →',
    cameraTitle:'चेहरा, आँखें, मूवमेंट और श्वास', camera{t(language,'instructions')}'कैमरे की ओर सीधे देखें, पूरा चेहरा दिखाई दे, रोशनी समान हो, कैमरा स्थिर रखें, स्वाभाविक रूप से पलकें झपकाएँ और आराम से रहें।', cameraStart:'कैमरा चेक शुरू करें', cameraRunning:'कैमरा चेक चल रहा है…', cameraCaptured:'✓ कैमरा डेटा लिया गया', review:'AI आकलन देखें →', assessment:'मल्टीमॉडल AI आकलन', assessmentText:'NUVYRA डेटा की गुणवत्ता जाँचता है, उपलब्ध मापों को आपकी व्यक्तिगत हिस्ट्री से तुलना करता है और समय के साथ बने रहने वाले बदलावों को देखता है।', run:'NUVYRA AI विश्लेषण चलाएँ', analyzing:'विश्लेषण हो रहा है…', score:'स्कोर', confidence:'विश्वसनीयता', quality:'डेटा गुणवत्ता', trend:'ट्रेंड', changed:'क्या बदला?', influenced:'परिणाम को किसने प्रभावित किया?', limitations:'महत्वपूर्ण सीमाएँ', history:'ग्राफ़िकल हिस्ट्री खोलें',
    notDisease:'किसी एक उत्तर में बदलाव किसी बीमारी या उसके कारण की पहचान नहीं करता।'
  },
  French: {
    daily:'CONTRÔLE IA QUOTIDIEN · ÉTAPE', baseline:'BASELINE PERSONNEL MULTIMODAL', feeling:'Comment vous sentez-vous aujourd’hui ?', feelingHelp:'Vos réponses décrivent votre expérience et votre contexte. Ce sont des observations déclarées, pas une évaluation médicale ou psychologique.', feelingIntro:'Cela donne à NUVYRA le contexte des mesures recueillies ensuite.',
    overall:'Ressenti général', better:'Mieux que d’habitude', same:'À peu près pareil', different:'Un peu différent', significant:'Sensiblement différent',
    energy:'Énergie', sleep:'Qualité du sommeil', stress:'{t(language,'stress')}', concentration:'{t(language,'concentration')}', comfort:'Confort physique', appetite:'Appétit', fatigue:'{t(language,'fatigue')}', noticed:'Ce que vous avez remarqué', observed:'Contexte facultatif à prendre en compte pour ce contrôle.',
    continue:'Continuer →', voice:'Voix et parole', chooseLanguage:'Choisissez votre langue', whatSay:'Que dire', differentPrompt:'Changer de consigne', instructions:'Instructions :', voice{t(language,'instructions')}'Trouvez un endroit assez calme, gardez le microphone à une distance adaptée et parlez naturellement pendant 20 secondes. Ne modifiez pas volontairement votre voix.', record:'Enregistrer 20 secondes', recording:'Enregistrement…', captured:'✓ Voix enregistrée', pitch:'Hauteur', sound:'Intensité sonore', waveform:'Caractéristique du signal', speech:'Activité vocale', continueCamera:'Continuer vers visage et mouvement →',
    cameraTitle:'Visage, yeux, mouvement et respiration', camera{t(language,'instructions')}'Regardez directement la caméra, gardez tout le visage visible, utilisez une lumière régulière, gardez la caméra stable, clignez naturellement et restez détendu.', cameraStart:'Démarrer le contrôle caméra', cameraRunning:'Contrôle caméra en cours…', cameraCaptured:'✓ Données caméra capturées', review:'Voir l’évaluation IA →', assessment:'Évaluation IA multimodale', assessmentText:'NUVYRA vérifie la qualité des données, gère les entrées manquantes, compare les mesures disponibles à votre historique personnel et recherche les changements persistants.', run:'Lancer l’analyse IA NUVYRA', analyzing:'Analyse en cours…', score:'{t(language,'score')}', confidence:'Confiance', quality:'Qualité des données', trend:'Tendance', changed:'Qu’est-ce qui a changé ?', influenced:'Qu’est-ce qui a influencé le résultat ?', limitations:'Limites importantes', history:'Ouvrir l’historique graphique',
    notDisease:'Un changement dans une réponse n’identifie pas une maladie ni sa cause.'
  }
};
const t = (language: AppLanguage, key: string) => COPY[language][key] || COPY.English[key] || key;

const moodDeviation: Record<string, number> = { better: 0.1, same: 0, different: 0.5, significant: 1 };
const promptFor = (language: AppLanguage, previous = '') => { const list = PROMPTS[language].filter(p => p !== previous); return list[Math.floor(Math.random() * list.length)] || PROMPTS[language][0]; };

async function extractVoice(blob: Blob): Promise<VoiceFeatures> {
  const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) throw new Error('Audio analysis is not supported by this browser.'); const context = new AudioContextClass();
  try { const audio = await context.decodeAudioData(await blob.arrayBuffer()); const data = audio.getChannelData(0); const step = Math.max(1, Math.floor(data.length / 160000)); let sum = 0, crossings = 0, count = 0, previous = 0; for (let i=0;i<data.length;i+=step) { const value=data[i]; sum+=value*value; count++; if(i>0 && ((previous<0&&value>=0)||(previous>=0&&value<0))) crossings++; previous=value; } const rms=Math.sqrt(sum/Math.max(count,1)); const zcr=crossings/Math.max(count-1,1); const frame=Math.max(256,Math.floor(audio.sampleRate*.025)); const hop=Math.max(128,Math.floor(audio.sampleRate*.01)); let frames=0,active=0,pitchTotal=0,pitchCount=0; for(let start=0;start+frame<data.length;start+=hop){let energy=0;for(let j=0;j<frame;j++)energy+=data[start+j]**2;const fr=Math.sqrt(energy/frame);frames++;if(fr>Math.max(rms*.35,.01)){active++;const minLag=Math.floor(audio.sampleRate/400),maxLag=Math.min(Math.floor(audio.sampleRate/70),frame-1);let bestLag=0,best=-Infinity;for(let lag=minLag;lag<=maxLag;lag++){let corr=0;for(let j=0;j<frame-lag;j+=4)corr+=data[start+j]*data[start+j+lag];if(corr>best){best=corr;bestLag=lag;}}const pitch=bestLag?audio.sampleRate/bestLag:0;if(pitch>=70&&pitch<=400){pitchTotal+=pitch;pitchCount++;}}} return {rms:Number(rms.toFixed(6)),zcr:Number(Math.min(1,zcr).toFixed(6)),pitch:Number((pitchCount?pitchTotal/pitchCount:0).toFixed(2)),speechActivity:Number((frames?active/frames:0).toFixed(4))}; } finally { await context.close(); }
}

export const CheckInMultimodalPage: React.FC = () => {
  const navigate=useNavigate(); const {language,setLanguage}=useLanguage(); const [step,setStep]=useState(1); const [prompt,setPrompt]=useState(()=>promptFor(language));
  const [mood,setMood]=useState('same'),[fatigue,set{t(language,'fatigue')}]=useState(2),[energy,set{t(language,'energy')}]=useState(7),[sleepQuality,setSleepQuality]=useState(7),[stress,set{t(language,'stress')}]=useState(3),[concentration,set{t(language,'concentration')}]=useState(7),[physicalComfort,setPhysicalComfort]=useState(8),[appetite,set{t(language,'appetite')}]=useState(7),[selectedSymptoms,setSelectedSymptoms]=useState<string[]>([]);
  const [voice,setVoice]=useState<VoiceFeatures|null>(null),[recording,setRecording]=useState(false),[voiceSeconds,setVoiceSeconds]=useState(20); const [camera,setCamera]=useState<Record<string,number>|null>(null),[capturing,setCapturing]=useState(false); const [result,setResult]=useState<AIAnalysisResponse|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
  const streamRef=useRef<MediaStream|null>(null),recorderRef=useRef<MediaRecorder|null>(null),videoRef=useRef<HTMLVideoElement|null>(null),canvasRef=useRef<HTMLCanvasElement|null>(null); useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);
  const info=(title:string,text:string)=><InfoButton title={title}>{text}</InfoButton>; const changeLanguage=(next:AppLanguage)=>{setLanguage(next);setPrompt(promptFor(next,prompt));}; const nextPrompt=()=>setPrompt(promptFor(language,prompt));
  const recordVoice=async()=>{setError(null);setVoice(null);setVoiceSeconds(20);try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const recorder=new MediaRecorder(stream,{mimeType:mime});const chunks:Blob[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{try{setVoice(await extractVoice(new Blob(chunks,{type:recorder.mimeType})))}catch{setError('The recording was captured, but voice feature extraction was unavailable.')}finally{stream.getTracks().forEach(t=>t.stop());streamRef.current=null;setRecording(false)}};recorderRef.current=recorder;recorder.start(250);setRecording(true);const started=performance.now();const countdown=window.setInterval(()=>{const remaining=Math.max(0,Math.ceil(20-(performance.now()-started)/1000));setVoiceSeconds(remaining);if(remaining<=0)window.clearInterval(countdown)},250);window.setTimeout(()=>{window.clearInterval(countdown);if(recorder.state!=='inactive')recorder.stop()},20000)}catch{setError('Microphone permission was unavailable. You can continue without voice data.');setRecording(false)}};
  const captureCamera=async()=>{setError(null);setCapturing(true);try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480,facingMode:'user'},audio:false});streamRef.current=stream;if(!videoRef.current||!canvasRef.current)throw new Error('Camera preview is unavailable.');videoRef.current.srcObject=stream;await videoRef.current.play();const canvas=canvasRef.current;canvas.width=160;canvas.height=120;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Camera analysis is unavailable.');const motion:number[]=[],luminance:number[]=[],eyeProxy:number[]=[],headProxy:number[]=[];let previous:Uint8ClampedArray|null=null;const end=performance.now()+10000;while(performance.now()<end){ctx.drawImage(videoRef.current,0,0,160,120);const pixels=ctx.getImageData(0,0,160,120).data;let lum=0,diff=0,top=0,bottom=0,left=0,right=0;for(let i=0;i<pixels.length;i+=4){const x=(i/4)%160,y=Math.floor((i/4)/160),value=.2126*pixels[i]+.7152*pixels[i+1]+.0722*pixels[i+2];lum+=value;if(y<45)top+=value;if(y>75)bottom+=value;if(x<55)left+=value;if(x>105)right+=value;if(previous)diff+=Math.abs(value-(.2126*previous[i]+.7152*previous[i+1]+.0722*previous[i+2]))}motion.push(diff/(160*120*255));luminance.push(lum/(160*120*255));eyeProxy.push(Math.abs(top-bottom)/(160*120*255));headProxy.push(Math.abs(left-right)/(160*120*255));previous=new Uint8ClampedArray(pixels);await new Promise(r=>window.setTimeout(r,200))}const mean=(a:number[])=>a.reduce((x,y)=>x+y,0)/Math.max(a.length,1),sd=(a:number[])=>{const m=mean(a);return Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/Math.max(a.length,1))},eye=mean(eyeProxy),head=mean(headProxy),movement=mean(motion);setCamera({face_motion:Number(movement.toFixed(6)),face_luminance_variability:Number(sd(luminance).toFixed(6)),face_blink_proxy:Number(Math.min(1,eye*10).toFixed(4)),blink_rate_per_minute:Number(Math.min(60,eye*60).toFixed(2)),eye_opening_proxy:Number(Math.max(0,Math.min(1,1-eye*10)).toFixed(4)),gait_motion:Number(movement.toFixed(6)),gait_variability:Number(sd(motion).toFixed(6)),gait_symmetry_proxy:Number(Math.max(0,Math.min(1,1-sd(headProxy)*10)).toFixed(4)),breathing_rate_per_minute:Number(Math.min(60,eye*60).toFixed(2)),breathing_variability:Number(sd(eyeProxy).toFixed(6)),head_motion:Number(head.toFixed(6)),head_motion_variability:Number(sd(headProxy).toFixed(6))})}catch(e:any){setError(e?.message||'Camera permission was unavailable. You can continue without camera data.')}finally{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCapturing(false)}};
  const analyze=async()=>{setLoading(true);setError(null);try{const response=await aiService.analyze({fatigue,mood_deviation:moodDeviation[mood]??0,symptom_burden:selectedSymptoms.length/symptoms.length,energy_level:energy,sleep_quality:sleepQuality,stress_level:stress,concentration_level:concentration,physical_comfort:physicalComfort,appetite_level:appetite,voice_language:language,...(voice?{voice_rms:voice.rms,voice_zero_crossing_rate:voice.zcr,voice_pitch_hz:voice.pitch,voice_speech_activity:voice.speechActivity}:{}),...(camera||{}),source_duration_seconds:voice?20:0});setResult(response)}catch(e:any){if(e?.status===401)navigate('/login');else setError(e?.message||'AI analysis failed.')}finally{setLoading(false)}};
  const toggle=(item:string)=>setSelectedSymptoms(current=>current.includes(item)?current.filter(x=>x!==item):[...current,item]);
  const help={voice:'Voice analysis measures pitch, sound strength, waveform characteristics and speech activity. These are computer measurements, not a diagnosis.',face:'Facial dynamics are visible changes between camera frames. Use even lighting, keep the camera steady and keep your face visible.',eye:'Eye and blink values are camera-based estimates, not an eye examination. Blink naturally.',movement:'Movement and gait values are visible-motion estimates, not a clinical walking test.',breathing:'Breathing-related values are visual rhythm estimates, not medical respiratory measurements. Breathe normally.',head:'Head movement describes visible changes in head position or motion.',baseline:'Your baseline is your own usual pattern learned from previous usable check-ins.',fusion:'The AI combines usable signals, handles noisy or missing data, and looks for changes that persist over time.'};
  const feelings=[['{t(language,'energy')}',energy,set{t(language,'energy')},'How energetic you feel right now.'],['{t(language,'sleep')}',sleepQuality,setSleepQuality,'How restorative your recent sleep felt; this is not a sleep study.'],['{t(language,'stress')}',stress,set{t(language,'stress')},'How much stress you feel right now; this is contextual self-report.'],['{t(language,'concentration')}',concentration,set{t(language,'concentration')},'How easy it feels to focus right now; this is not a cognitive test.'],['{t(language,'comfort')}',physicalComfort,setPhysicalComfort,'How physically comfortable you feel right now.'],['{t(language,'appetite')}',appetite,set{t(language,'appetite')},'How your appetite feels compared with your usual pattern.']] as const;
  return <div className="max-w-4xl mx-auto space-y-6 py-4"><div className="flex justify-between text-xs font-mono text-slate-400"><span>{t(language,'daily')} {step}/4</span><span className="text-sky-400">{t(language,'baseline')}</span></div>{error&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200">{error}</div>}
    {step===1&&<section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-7"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">{t(language,'feeling')}</h2>{info('Your current feeling','These answers capture your own experience and context. They are self-reported observations, not a medical or psychological assessment.')}</div><p className="text-sm text-slate-400 mt-1">{t(language,'feelingIntro')}</p></div><div><div className="text-xs uppercase tracking-wider text-slate-500 mb-3">{t(language,'overall')}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries({better:'{t(language,'better')}',same:'{t(language,'same')}',different:'{t(language,'different')}',significant:'{t(language,'significant')}'}).map(([id,label])=><button key={id} onClick={()=>setMood(id)} className={`p-4 rounded-xl border text-left ${mood===id?'border-sky-500 bg-sky-500/10 text-white':'border-slate-800 bg-slate-900 text-slate-300'}`}>{label}</button>)}</div></div><div className="grid md:grid-cols-2 gap-x-6 gap-y-5">{feelings.map(([label,value,setter,description])=><div key={label}><div className="flex justify-between text-xs text-slate-300"><span className="flex items-center gap-2">{label}{info(label,description)}</span><span>{value}/10</span></div><input aria-label={label} className="w-full mt-2" type="range" min="0" max="10" value={value} onChange={e=>setter(Number(e.target.value))}/></div>)}</div><div><div className="flex justify-between text-xs text-slate-300"><span className="flex items-center gap-2">{t(language,'fatigue')}{info('{t(language,'fatigue')}','How tired you feel today. 0 means not tired; 10 means very tired.')}</span><span>{fatigue}/10</span></div><input aria-label="{t(language,'fatigue')}" className="w-full mt-2" type="range" min="0" max="10" value={fatigue} onChange={e=>set{t(language,'fatigue')}(Number(e.target.value))}/></div><div><div className="flex items-center gap-2 text-xs text-slate-400 mb-2">{t(language,'noticed')}{info('Observations','{t(language,'observed')}')}</div><div className="flex flex-wrap gap-2">{symptoms.map(item=><button key={item} onClick={()=>toggle(item)} className={`px-3 py-1.5 rounded-lg border text-xs ${selectedSymptoms.includes(item)?'border-teal-400 bg-teal-500/10 text-teal-300':'border-slate-800 text-slate-400'}`}>{selectedSymptoms.includes(item)?'✓ ':'+ '}{item}</button>)}</div></div><div className="rounded-xl border border-slate-800 bg-slate-950/30 p-4 text-xs leading-5 text-slate-500">NUVYRA combines these answers with available voice, camera and clinical context. A change in one answer does not identify a disease or its cause.</div><button onClick={()=>setStep(2)} className="w-full bg-gradient-to-r from-sky-500 to-teal-500 text-slate-950 font-semibold py-3 rounded-xl">{t(language,'continue')}</button></section>}
    {step===2&&<section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">{t(language,'voice')}</h2>{info('Voice analysis',help.voice)}</div><div><div className="text-sm font-semibold text-white mb-2">{t(language,'chooseLanguage')}</div><div className="grid grid-cols-3 gap-2">{(['English','Hindi','French'] as AppLanguage[]).map(l=><button key={l} onClick={()=>changeLanguage(l)} className={`rounded-xl border px-3 py-2 text-sm ${language===l?'bg-white text-slate-950 border-white':'border-slate-700 text-slate-300'}`}>{l==='Hindi'?'हिन्दी':l==='French'?'Français':l}</button>)}</div></div><div className="rounded-xl bg-slate-900 p-5"><div className="text-xs uppercase text-slate-400">{t(language,'whatSay')}</div><p className="mt-2 text-base leading-7 text-white">{prompt}</p><button onClick={nextPrompt} className="mt-3 text-sm text-sky-300 underline">{t(language,'differentPrompt')}</button></div><div className="rounded-xl border border-slate-800 p-4 text-sm leading-6 text-slate-300"><strong className="text-white">{t(language,'instructions')}</strong> {t(language,'voiceInstructions')}</div><button disabled={recording} onClick={recordVoice} className="mx-auto block px-6 py-3 rounded-xl bg-sky-500 disabled:opacity-50 text-slate-950 font-semibold">{recording?`Recording… ${voiceSeconds}s`:voice?'{t(language,'captured')}':'{t(language,'record')}'}</button>{voice&&<div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-center text-xs text-slate-400">{[['{t(language,'pitch')}',`${voice.pitch?voice.pitch.toFixed(0):'Not available'} Hz`],['{t(language,'sound')}',voice.rms.toFixed(4)],['{t(language,'waveform')}',voice.zcr.toFixed(3)],['{t(language,'speech')}',`${Math.round(voice.speechActivity*100)}%`]].map(([title,value])=><div key={String(title)} className="rounded-xl bg-slate-900 p-3"><div>{title as string}</div><b className="block mt-1 text-white">{value as string}</b></div>)}</div>}<button disabled={!voice} onClick={()=>setStep(3)} className="w-full rounded-xl bg-teal-500 py-3 font-semibold text-slate-950 disabled:opacity-40">{t(language,'continueCamera')}</button></section>}
    {step===3&&<section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">{t(language,'cameraTitle')}</h2>{info('Camera measurements',`${help.face} ${help.eye} ${help.movement} ${help.breathing} ${help.head}`)}</div><div className="rounded-xl border border-slate-800 p-4 text-sm leading-6 text-slate-300"><strong className="text-white">Camera instructions:</strong> {t(language,'cameraInstructions')}</div><video ref={videoRef} muted playsInline className="w-full max-w-md mx-auto rounded-xl bg-black aspect-video object-cover scale-x-[-1]"/><canvas ref={canvasRef} className="hidden"/><button disabled={capturing} onClick={captureCamera} className="mx-auto block px-6 py-3 rounded-xl bg-teal-500 disabled:opacity-50 text-slate-950 font-semibold">{capturing?'{t(language,'cameraRunning')}':camera?'{t(language,'cameraCaptured')}':'{t(language,'cameraStart')}'}</button>{camera&&<div className="grid grid-cols-2 md:grid-cols-3 gap-3">{Object.entries(camera).map(([key,value])=><div key={key} className="rounded-xl bg-slate-900 p-3"><div className="text-xs text-slate-400">{key.replace(/_/g,' ')}</div><b className="block mt-1 text-white">{Number(value).toFixed(4)}</b></div>)}</div>}<button disabled={!camera} onClick={()=>setStep(4)} className="w-full rounded-xl bg-sky-500 py-3 font-semibold text-slate-950 disabled:opacity-40">{t(language,'review')}</button></section>}
    {step===4&&<section className="rounded-2xl bg-[#111827] border border-slate-800 p-6 space-y-6"><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-white">{t(language,'assessment')}</h2>{info('How the AI assesses data',`${help.fusion} ${help.baseline}`)}</div>{!result?<><p className="text-sm leading-6 text-slate-400">{t(language,'assessmentText')}</p><button disabled={loading} onClick={analyze} className="w-full bg-gradient-to-r from-sky-500 to-teal-500 disabled:opacity-50 text-slate-950 font-semibold py-3 rounded-xl">{loading?'{t(language,'analyzing')}':'{t(language,'run')}'}</button></>:<div className="space-y-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['{t(language,'score')}',result.overall_score.toFixed(1)],['{t(language,'confidence')}',`${Math.round(result.confidence*100)}%`],['{t(language,'quality')}',`${Math.round(result.data_quality_score*100)}%`],['{t(language,'trend')}',result.trend]].map(([t,v])=><div key={String(t)} className="rounded-xl bg-slate-900 p-4"><div className="text-xs text-slate-400">{t as string}</div><b className="mt-2 block text-white">{v as string}</b></div>)}</div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">{t(language,'changed')}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{result.explanation}</p></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">{t(language,'influenced')}</h3><ul className="mt-2 space-y-1 text-sm text-slate-400">{(result.top_drivers||[]).map(d=><li key={d}>• {d}</li>)}</ul></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">{t(language,'limitations')}</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-slate-500">{(result.limitations||[]).map(x=><li key={x}>• {x}</li>)}</ul></div><button onClick={()=>navigate('/trends')} className="w-full rounded-xl bg-sky-500 py-3 font-semibold text-slate-950">{t(language,'history')}</button></div>}</section>}
  </div>;
};
